"use strict";

export const countries = [
  "berylia",
  "crimsonia",
  "revalia",
  "netoria",
  "random",
];
export const citiesBerylia = [
  "Bancroft",
  "Moazac",
  "Lambeck",
  "Durgan",
  "Portsmith",
  "Kral",
  "Erack",
  "Glassmoor",
  "Elev",
  "Koat",
  "Kranin",
  "Tanix",
  "Carcastle",
  "Zechan",
  "Janford",
  "Wildehill",
  "Vundan",
  "Tettlewick",
  "Bakun",
  "Paldar",
  "Norville",
  "Mizim",
  "Pineland",
  "Vear",
  "Adeasa",
];

export const citiesCrimsonia = [
  "Strin",
  "Streka",
  "Ugrark",
  "Vrodnard",
  "Roseiron",
  "Daka",
  "Srodon",
  "Vlando",
  "Upul",
  "Xurg",
  "Olkburg",
  "Goit",
  "Drespus",
];

export const citiesRevalia = [
  "Valora",
  "Eldhrim",
  "Fjallborg",
  "Njordheim",
  "Runestad",
];

export const citiesNetoria = [
  "Norvayne",
  "Valharm",
  "Marvyn",
  "Solhaven",
  "Elden",
  "Stornholm",
  "Havenbrook",
];
export const cities = [
  ...citiesBerylia,
  ...citiesCrimsonia,
  ...citiesRevalia,
  ...citiesNetoria,
];

export const descLvl1 = [
  "SQL Injection via login form bypass (CVE-2024-10001)",
  "Remote code execution in API endpoint (CVE-2024-10002)",
  "Privilege escalation via kernel flaw (CVE-2024-10003)",
  "Heap overflow in image parsing library (CVE-2024-10004)",
  "Arbitrary file read in config file parser (CVE-2024-10005)",
  "Bypass authentication via session fixation (CVE-2024-10006)",
  "Command injection in web shell upload (CVE-2024-10007)",
  "SSRF attack leaking internal resources (CVE-2024-10008)",
  "Race condition in user privilege assignment (CVE-2024-10009)",
  "Buffer overflow in XML parser (CVE-2024-10010)",
  "Deserialization attack in web API (CVE-2024-10011)",
  "Unrestricted file upload leads to RCE (CVE-2024-10012)",
  "Stored XSS in profile image metadata (CVE-2024-10013)",
  "Path traversal allows arbitrary file deletion (CVE-2024-10014)",
  "Memory corruption via malformed network packets (CVE-2024-10015)",
  "Clickjacking on financial transaction page (CVE-2024-10016)",
  "DNS rebinding attack exposing local services (CVE-2024-10017)",
  "IDOR vulnerability exposing customer invoices (CVE-2024-10018)",
  "Unprotected admin panel accessible via parameter tampering (CVE-2024-10019)",
  "Zero-day exploit in mobile authentication flow (CVE-2024-10020)",
];
export const descLvl2 = [
  "Fake invoice email impersonating Microsoft",
  "CEO fraud email requesting urgent wire transfer",
  "Phishing site mimicking bank login page",
  "Malicious PDF attachment delivering credential harvester",
  "Voice phishing call pretending to be IT support",
  "Gift card scam targeting HR department",
  "Spear phishing email with malware-laden job offer",
  "Fake security alert redirecting to credential-stealing site",
  "Lookalike domain tricking employees into login submission",
  "Smishing campaign using fake delivery notifications",
  "Compromised supplier email requesting payment changes",
  "Social engineering attack posing as a government agency",
  "Malicious QR code leading to credential theft",
  "Compromised cloud storage link spreading malware",
  "AI-generated deepfake video call impersonating executive",
  "Subscription renewal scam harvesting credit card details",
  "Fake LinkedIn job invitation leading to credential theft",
  "Email spoofing attack impersonating internal IT team",
  "Survey scam collecting personal data for identity theft",
  "Fake tech support popup prompting remote access installation",
];
export const descLvl3 = [
  "Ransomware encrypting company files with AES-256",
  "Trojan disguised as a banking application",
  "Spyware capturing keystrokes and screenshots",
  "Worm propagating via SMB protocol exploitation",
  "Rootkit embedding itself into system kernel",
  "Malvertising campaign injecting drive-by malware",
  "Botnet infection launching DDoS attacks",
  "Crypto-mining malware draining CPU resources",
  "Fileless malware executing in system memory",
  "Backdoor allowing persistent attacker access",
  "Polymorphic virus evading signature-based detection",
  "Trojanized software update distributing malicious payload",
  "Stealer malware exfiltrating stored passwords",
  "Keylogger capturing credentials from online forms",
  "Logic bomb triggered after specific employee termination",
  "Adware injecting unwanted browser extensions",
  "USB drop attack deploying remote access trojan",
  "Supply chain attack inserting malware into firmware updates",
  "Rogue antivirus software scamming users with fake threats",
  "Hidden RAT (Remote Access Trojan) granting full system control",
];
export const attackDesc = [descLvl1, descLvl2, descLvl3];

export const btExploits = [
  // Exploits
  "Modbus write overflow on",
  "VPN auth bypass on",
  "Remote shell via SNMP on",
  "Memory leak in SCADA on",
  "Auth bypass using JWT flaw on",
  "Telnet backdoor exploit on",
  "Buffer overrun in parser on",
  "Logic flaw in RPC handler on",
  "Race condition in RTU auth on",
  "Stack smash in driver code on",
  "XML bomb crash on",
  "Weak SSH keys found on",
  "Firmware downgrade trick on",
  "Session hijack via token leak on",
  "Path traversal in log viewer on",
  "UDP flood triggers DoS on",
  "Unsafe deserialization on",
  "Old TLS cipher suite on",
  "Hardcoded creds in firmware on",
  "ICMP tunneling detected on",
];

export const btPhising = [
  // Phishing
  "Fake sysadmin email to",
  "Spoofed update notice for",
  "Login lure from fake vendor to",
  "Malicious PDF sent to",
  "Voice call pretending IT at",
  "Fake patch link sent to",
  "Impersonated audit request at",
  "Bogus incident alert for",
  "LinkedIn lure targeting",
  "Email spoofed from ops to",
  "QR login scam targeting",
  "Compromised vendor request to",
  "Clone site asking login from",
  "Smishing via SMS to staff at",
  "Fake CEO request to finance at",
  "Invoice phishing to accounts at",
  "Survey phishing link sent to",
  "Urgent wire fraud targeting",
  "Spoofed IT reset email at",
  "Fake compliance doc sent to",
];

export const btMalware = [
  // Malware
  "RAT beaconing from",
  "Wiper malware on",
  "Keylogger deployed on",
  "Crypto miner active on",
  "Rootkit hides in",
  "USB worm on",
  "Spyware logs screens on",
  "DNS tunneling via",
  "Dropper loads Trojan on",
  "Polymorphic code on",
  "Fileless loader on",
  "Backdoor in bootloader on",
  "Botnet activity from",
  "Fake AV running on",
  "Persistence implant in",
  "Stealer grabs creds on",
  "Malvertising hit on",
  "Trojan camouflaged in update on",
  "SMB worm outbreak on",
  "Ransom note found on",
];

export const btAttackDesc = [btExploits, btPhising, btMalware];

export const testData = [
  { TS: 1746092767731, begin: "crimsonia", end: "bt02", target: "satellite" },
  { TS: 1746092769731, begin: "crimsonia", end: "bt04", target: "satellite" },
  { TS: 1746092772731, begin: "crimsonia", end: "bt12", target: "satellite" },
  { TS: 1746092782731, begin: "crimsonia", end: "bt01", target: "satellite" },
  { TS: 1746092785731, begin: "crimsonia", end: "bt06", target: "power plant" },
  { TS: 1746092788731, begin: "crimsonia", end: "bt10", target: "satellite" },
  /*   { TS: 1746092791731, begin: "crimsonia", end: "bt15", target: "satellite" },
  { TS: 1746092794731, begin: "crimsonia", end: "bt02", target: "satellite" },
  { TS: 1746092797731, begin: "crimsonia", end: "bt17", target: "power plant" },
  { TS: 1746092800731, begin: "crimsonia", end: "bt16", target: "satellite" },
  { TS: 1746092803731, begin: "crimsonia", end: "bt12", target: "power plant" },
  { TS: 1746092806731, begin: "crimsonia", end: "bt11", target: "satellite" },
  { TS: 1746092809731, begin: "crimsonia", end: "bt05", target: "satellite" },
  { TS: 1746092812731, begin: "crimsonia", end: "bt12", target: "power plant" },
  { TS: 1746092827731, begin: "crimsonia", end: "bt01", target: "satellite" },
  { TS: 1746092830731, begin: "crimsonia", end: "bt06", target: "satellite" },
  { TS: 1746092833731, begin: "crimsonia", end: "bt10", target: "power plant" },
  { TS: 1746092836731, begin: "crimsonia", end: "bt15", target: "satellite" },
  { TS: 1746092839731, begin: "crimsonia", end: "bt02", target: "satellite" },
  { TS: 1746092842731, begin: "crimsonia", end: "bt17", target: "satellite" },
  { TS: 1746092845731, begin: "crimsonia", end: "bt16", target: "power plant" },
  { TS: 1746092848731, begin: "crimsonia", end: "bt12", target: "satellite" },
  { TS: 1746092851731, begin: "crimsonia", end: "bt02", target: "satellite" },
  { TS: 1746092854731, begin: "crimsonia", end: "bt17", target: "power plant" },
  { TS: 1746092857731, begin: "crimsonia", end: "bt16", target: "satellite" },
  { TS: 1746092860731, begin: "crimsonia", end: "bt12", target: "power plant" },
  { TS: 1746092863731, begin: "crimsonia", end: "bt11", target: "satellite" },
  { TS: 1746092875731, begin: "crimsonia", end: "bt05", target: "power plant" },
  { TS: 1746092878731, begin: "crimsonia", end: "bt12", target: "satellite" },
  { TS: 1746092880731, begin: "crimsonia", end: "bt01", target: "power plant" },
  { TS: 1746092882731, begin: "crimsonia", end: "bt06", target: "satellite" },
  { TS: 1746092884731, begin: "crimsonia", end: "bt10", target: "satellite" },
  { TS: 1746092886731, begin: "crimsonia", end: "bt15", target: "satellite" }, */
  //{ TS: 99999999999999999999, begin: "crimsonia", end: "bt15", target: "satellite" }
];
