"use strict";
export const countries = [
  "Berylia",
  "Crimsonia",
  "Revalia",
  "Netoria",
  "random",
];
export const citiesBerylia = [
  "Bancroft",
  "Moazac",
  "Lambeck",
  "Durgan",
  "Portsmith",
  "Kral",
  "Erack",
  "Glassmoor",
  "Elev",
  "Koat",
  "Kranin",
  "Tanix",
  "Carcastle",
  "Zechan",
  "Janford",
  "Wildehill",
  "Vundan",
  "Tettlewick",
  "Bakun",
  "Paldar",
  "Norville",
  "Mizim",
  "Pineland",
  "Vear",
  "Adeasa",
];

export const citiesCrimsonia = [
  "Strin",
  "Streka",
  "Ugrark",
  "Vrodnard",
  "Roseiron",
  "Daka",
  "Srodon",
  "Vlando",
  "Upul",
  "Xurg",
  "Olkburg",
  "Goit",
  "Drespus",
  "West_Point",
];

export const citiesRevalia = [
  "Valora",
  "Eldhrim",
  "Fjallborg",
  "Njordheim",
  "Runestad",
];

export const citiesNetoria = [
  "Norvayne",
  "Valharm",
  "Marvyn",
  "Solhaven",
  "Elden",
  "Stornholm",
  "Havenbrook",
];
export const cities = [
  ...citiesBerylia,
  ...citiesCrimsonia,
  ...citiesRevalia,
  ...citiesNetoria,
];

export const descLvl1 = [
  "SQL Injection via login form bypass (CVE-2024-10001)",
  "Remote code execution in API endpoint (CVE-2024-10002)",
  "Privilege escalation via kernel flaw (CVE-2024-10003)",
  "Heap overflow in image parsing library (CVE-2024-10004)",
  "Arbitrary file read in config file parser (CVE-2024-10005)",
  "Bypass authentication via session fixation (CVE-2024-10006)",
  "Command injection in web shell upload (CVE-2024-10007)",
  "SSRF attack leaking internal resources (CVE-2024-10008)",
  "Race condition in user privilege assignment (CVE-2024-10009)",
  "Buffer overflow in XML parser (CVE-2024-10010)",
  "Deserialization attack in web API (CVE-2024-10011)",
  "Unrestricted file upload leads to RCE (CVE-2024-10012)",
  "Stored XSS in profile image metadata (CVE-2024-10013)",
  "Path traversal allows arbitrary file deletion (CVE-2024-10014)",
  "Memory corruption via malformed network packets (CVE-2024-10015)",
  "Clickjacking on financial transaction page (CVE-2024-10016)",
  "DNS rebinding attack exposing local services (CVE-2024-10017)",
  "IDOR vulnerability exposing customer invoices (CVE-2024-10018)",
  "Unprotected admin panel accessible via parameter tampering (CVE-2024-10019)",
  "Zero-day exploit in mobile authentication flow (CVE-2024-10020)",
];
export const descLvl2 = [
  "Fake invoice email impersonating Microsoft",
  "CEO fraud email requesting urgent wire transfer",
  "Phishing site mimicking bank login page",
  "Malicious PDF attachment delivering credential harvester",
  "Voice phishing call pretending to be IT support",
  "Gift card scam targeting HR department",
  "Spear phishing email with malware-laden job offer",
  "Fake security alert redirecting to credential-stealing site",
  "Lookalike domain tricking employees into login submission",
  "Smishing campaign using fake delivery notifications",
  "Compromised supplier email requesting payment changes",
  "Social engineering attack posing as a government agency",
  "Malicious QR code leading to credential theft",
  "Compromised cloud storage link spreading malware",
  "AI-generated deepfake video call impersonating executive",
  "Subscription renewal scam harvesting credit card details",
  "Fake LinkedIn job invitation leading to credential theft",
  "Email spoofing attack impersonating internal IT team",
  "Survey scam collecting personal data for identity theft",
  "Fake tech support popup prompting remote access installation",
];
export const descLvl3 = [
  "Ransomware encrypting company files with AES-256",
  "Trojan disguised as a banking application",
  "Spyware capturing keystrokes and screenshots",
  "Worm propagating via SMB protocol exploitation",
  "Rootkit embedding itself into system kernel",
  "Malvertising campaign injecting drive-by malware",
  "Botnet infection launching DDoS attacks",
  "Crypto-mining malware draining CPU resources",
  "Fileless malware executing in system memory",
  "Backdoor allowing persistent attacker access",
  "Polymorphic virus evading signature-based detection",
  "Trojanized software update distributing malicious payload",
  "Stealer malware exfiltrating stored passwords",
  "Keylogger capturing credentials from online forms",
  "Logic bomb triggered after specific employee termination",
  "Adware injecting unwanted browser extensions",
  "USB drop attack deploying remote access trojan",
  "Supply chain attack inserting malware into firmware updates",
  "Rogue antivirus software scamming users with fake threats",
  "Hidden RAT (Remote Access Trojan) granting full system control",
];
export const attackDesc = [descLvl1, descLvl2, descLvl3];
